version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - gocritic

  settings:
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
          disabled: false
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - unnamedResult
        - hugeParam

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
